transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib nios_setup
vmap nios_setup nios_setup
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/nios_setup.v}
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_mm_interconnect_0.v}
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_uart.v}
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_switch.v}
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_onchip_memory2_0.v}
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_onchip_memory.v}
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_nios2e.v}
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_nios2e_cpu.v}
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_nios2e_cpu_debug_slave_sysclk.v}
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_nios2e_cpu_debug_slave_tck.v}
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_nios2e_cpu_debug_slave_wrapper.v}
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_nios2e_cpu_test_bench.v}
vlog -vlog01compat -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_led.v}
vlog -vlog01compat -work work +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/ethernet_packet_analyzer.v}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_irq_mapper.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_mm_interconnect_0_rsp_mux_001.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_mm_interconnect_0_rsp_demux_001.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_mm_interconnect_0_cmd_mux_001.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_mm_interconnect_0_cmd_demux_001.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_mm_interconnect_0_router_003.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_mm_interconnect_0_router_002.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_mm_interconnect_0_router_001.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/nios_setup_mm_interconnect_0_router.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work nios_setup +incdir+C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules {C:/Users/robertmadsen/Desktop/ethernet_packet_analyzer/ethernet_packet_analyzer_project/nios_setup/synthesis/submodules/altera_merlin_master_translator.sv}

